### ISSUE TITLE
room is not shown in calendar search

### ISSUE THREAD

**Issue by himpierre** [nextcloud/calendar_resource_management#10]
Hello!

I'm trying to add a room to an appointment but the search is not bringing up the only room I created so far. Is this supposed to work currently?

`
root@nextcloud:/var/www/nextcloud.dev./htdocs# sudo -u www-data php occ calendar-resource:resources:listBuildings:
+----+-------+---------+-------------+-----------------------+
| ID | Name  | Address | Description | Wheelchair Accessible |
+----+-------+---------+-------------+-----------------------+
| 1  | box80 |         |             | no                    |
+----+-------+---------+-------------+-----------------------+
Rooms:
+----+-----+----------------+------------------+-----------------+-----------+----------------+----------+-------------+-------+--------------------+----+-----------+------------+-----------------------+
| ID | UID | Name           | Located in       | Email           | Room Type | Contact Person | Capacity | Room Number | Phone | Video Conferencing | TV | Projector | Whiteboard | Wheelchair Accessible |
+----+-----+----------------+------------------+-----------------+-----------+----------------+----------+-------------+-------+--------------------+----+-----------+------------+-----------------------+
| 9  | fh  | friedrichshain | address, 3rd floor | ts@domain.de | 0         | thomas         | 10       |             | yes   | yes                | no | no        | no         | no                    |
+----+-----+----------------+------------------+-----------------+-----------+----------------+----------+-------------+-------+--------------------+----+-----------+------------+-----------------------+
`

**Comment by ChristophWurst** [comment]
you might have to be patient, resources are picked up by a cron job. if that job hasn't run yet then the rooms won't show up.

**Comment by BenBo17** [comment]
Hi. Sorry for reopening this, but I experience the same issue even, after executing cron manually multiple times.
Can someone help with this? 

Just to be sure: The created resource would appear in the "resources" section on a newly created calendar event, right?

**Comment by st3iny** [comment]
@BenBo17 Yeah but you need to search for resources before they start to appear.

If it still doesn't work please open a new issue.
