### ISSUE TITLE
Deleting stories, buildings - how to?

### ISSUE THREAD

**Issue by motioncompany** [nextcloud/calendar_resource_management#108]
### Steps to reproduce

I have 
```
Buildings:
+----+------------+-----------------------------------+-------------+-----------------------+
| ID | Name       | Address                           | Description | Wheelchair Accessible |
+----+------------+-----------------------------------+-------------+-----------------------+
| 1  | TSV Places | On the way 1, 12345 Cityline      |	            | no                    |
+----+------------+-----------------------------------+-------------+-----------------------+
Stories:
+----+------------+--------------+
| ID | Located in | Display Name |
+----+------------+--------------+
| 1  | TSV Places | A            |
| 2  | TSV Places | B            |
| 3  | TSV Places | C            |
`+----+------------+--------------+```
```

calendar-resource:resource:delete

### Expected behavior

How to delete stories and/or buildings? Need an example of the correct comand please

### Actual behavior

 Not enough arguments (missing: "type, resource_id")

### App version

v0.6.0

**Comment by st3iny** [comment]
You need to specify the type of resource and its id.

## Examples:
- Delete story with id 1: `occ calendar-resource:resource:delete story 1`
- Delete building with id 1 (and all contained stories): `occ calendar-resource:resource:delete building 1`
