### ISSUE TITLE
rooms in same building should share same email

### ISSUE THREAD

**Issue by Zweihorn** [nextcloud/calendar_resource_management#119]
### Steps to reproduce

1. create building
2. create at leat one floor i.e. "story" for a.m. building
3. create first room in a.m. floor with new uid "room1" and an email address e.g., "fake@nextcloud-berlin.de"
4. try to establish second room in a.m. floor with new uid "room2" and same email address e.g., "fake@nextcloud-berlin.de"

### Expected behavior

create room independent from email and without any error as applicable

Furthermore:
1. all rooms in the same building should be able to share same email;
1. optional rooms could allow different emails in same building;
1. there should be NO restriction for any rooms in sharing the same email

### Actual behavior

**error message** was:
`Could not create entry: An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'fake@nextcloud-berlin.de' for key 'calresources_rooms_eml'`

### App version

0.7.0

### Additional info

ref #117 
ref #96

**Comment by st3iny** [comment]
The email address serves as the unique identifier of a room or resource. This is a limitation of the CalDAV backend and can't be worked around.

**Comment by Zweihorn** [comment]
@st3iny 

IMHO the workaround should be user driven and thus using fake email entries, I presume.

**Comment by Zweihorn** [comment]
Ref my theme i.e. article [Calendar_resource_management & create rooms](https://help.nextcloud.com/t/calendar-resource-management-create-rooms/192562) on the [Help Forum](https://help.nextcloud.com/)

**Comment by Mannshoch** [comment]
May check if your mail provider support mails with + that way you could use one mail adress e.g. user@example.com and use for the room user+ressource1@example.com

**Comment by Mondane** [comment]
another thing could be to use aliasses or forwards
