### ISSUE TITLE
"Room availability" button not visible

### ISSUE THREAD

**Issue by thomai** [nextcloud/calendar_resource_management#137]
### Steps to reproduce

Steps to reproduce (at least on my instance, the behavior is always the same):
1. Create resources with documented OCC commands
2. Create new event "test"
3. Click on "Resources" tab

### Expected behavior

I would expect to see the button "Room availability" (as documented [here](https://docs.nextcloud.com/server/latest/user_manual/en/groupware/calendar.html#room-availability)).

### Actual behavior

No button "Room availability" to get an overview of all resources available at the chosen timeslot.
![image](https://github.com/user-attachments/assets/04c324fc-e02b-4352-a50a-8085ce34da65)

### App version

Calendar Resource Management 0.8 (Nextcloud 29.0.3)

### Additional info

If I start typing the resource's name in the text field "Search for resources or rooms", I can find the created resources.

**Comment by st3iny** [comment]
The feature requires Calendar v5.0.0 or newer. The documentation is misleading and should be corrected.

**Comment by thomai** [comment]
@st3iny Thanks for the clarification.
