### ISSUE TITLE
always "too many arguments"

### ISSUE THREAD

**Issue by leon1995** [nextcloud/calendar_resource_management#158]
### Steps to reproduce

1. I always get a `too many arguments` error when creating resources.
2. create your own command or use from the example `occ calendar-resource:building:create --address="Testweg 23, 12345 Berlin, Germany" "SpaceZ office Berlin"`
3. get error `Too many arguments to "calendar-resource:building:create" command, expected arguments "display_name". `

### Expected behavior

create resource

### Actual behavior

get error `Too many arguments to "calendar-resource:building:create" command, expected arguments "display_name". `

### App version

0.8.0

### Additional info

what do you need?

**Comment by st3iny** [comment]
Hi, thanks for the report.

I can not reproduce this locally on Nextcloud stable30 and app stable0.8.

```
$ occ stable30 calendar-resource:building:create --address="Testweg 23, 12345 Berlin, Germany" "SpaceZ office Berlin"
Created new Building with ID:
2
```

Perhaps there are some issues with argument quoting? Are you using docker or a custom occ script where word splitting might mess up the arguments?

**Comment by leon1995** [comment]
I am using a shortcut `docker exec --user www-data -it nextcloud-aio-nextcloud php occ $*` as an executable in the `PATH`. If I execute `docker exec --user www-data -it nextcloud-aio-nextcloud php occ calendar-resource:building:create --address="Testweg 23, 12345 Berlin, Germany" "SpaceZ office Berlin"` it works fine. So somewhere my custom command is wrong. It works with all the other occ commands tho that I have been using so far (I think none of them had optional arguments...)
