### ISSUE TITLE
Ressources (rooms) can be booked multiple times in same time frame

### ISSUE THREAD

**Issue by jonathanmmm** [nextcloud/calendar_resource_management#19]
Hi,

I created a room and I could search for this (didn't show up without searching) and booking it on two different accounts and even on the same account ones from 10-11 a.m. and ones the whole day. 

Maybe I have done something wrong or is this plugin not forbidding using the same room twice in the same time period?

**Comment by ChristophWurst** [comment]
This is the back end. This app has no control over scheduling. Scheduling is done in the caldav backend of Nextcloud. Resources can be added to more than one event. Only one time it will show as accepted. The other times it will show with declined participation.

Let's move this to https://help.nextcloud.com/c/support/7 if you have further question or https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C+0.+Needs+triage&template=Bug_report.md if you are sure this is a bug.

Please provide the full .ics of the affected events. Then we can check the participation status of the resources.

**Comment by jonathanmmm** [comment]
Ok, maybe I need to wait longer, the acception didn't come on neither of the events. 
I waited now over a day and still not accepted the invite, but this is then a calendar/server problem and not of this plugin, right? Has it maybe to do, that I gave this room an email and it tries to send an email and waits for confirmation?

**Comment by ChristophWurst** [comment]
It comes immediately. What client did you use? I observed that Calendar events scheduled resources immediately but with Thunderbird they were stale.

As said before we should move support questions to the forum. If there is a bug with scheduling then it shall be opened as https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C+0.+Needs+triage&template=Bug_report.md following the issue template.

**Comment by jonathanmmm** [comment]
I have only used the nextcloud webinterface.
I will probably create an issue and then link it to this one, will close this for now.

**Comment by manu-p** [comment]
> I have only used the nextcloud webinterface. I will probably create an issue and then link it to this one, will close this for now.

@jonathanmmm did you create the issue you were mentioning? Could you give here the link.

**Comment by jonathanmmm** [comment]
The

> > I have only used the nextcloud webinterface. I will probably create an issue and then link it to this one, will close this for now.
> 
> @jonathanmmm did you create the issue you were mentioning? Could you give here the link.

There it is

**Comment by manu-p** [comment]
Hi,

As @ChristophWurst mentioned, I can see the resource as 'booked' when a first invite is done, then the resource is declined for the subsequent bookings.
The organizer of the vent has to check the participants in order to make sure he's got the resource, or not.
Not user friendly at all.

When an 'real' email is provided for the resource (in my case a resource specific alias that pushes the mails to my mailbox for tests), I receive an invite email each time the resource is booked, but no other mail to confirm or reject the reservation (which would be from the 'back end' if I followed correctly the previous explanations.

Maybe your case, @jonathanmmm is related to your docker based configuration?

**Comment by jonathanmmm** [comment]
I thought a room that is available should be automatically accept an invite. Or is this wrong?

**Comment by manu-p** [comment]
That's what happen on my config, @jonathanmmm
