### ISSUE TITLE
Cannot create restriction

### ISSUE THREAD

**Issue by jasperroloff** [nextcloud/calendar_resource_management#25]
When creating a restriction, the following error appears:

```
# ./occ calendar-resource:restriction:create room 1 Test
Could not create entry: An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1364 Field 'entity_id' doesn't have a default value
```

I think that this has to do with this line: https://github.com/nextcloud/calendar_resource_management/blob/b3b448af37b07c55f01fe793e80ae296e4da35fe/lib/Command/CreateRestriction.php#L76
If I guess right, there should be `setEntityId($entityId);` instead of `setEntityType($entityId);`

**Comment by ChristophWurst** [comment]
That seems right from a code perspective. @miaulalala can you confirm? @jasperroloff feel free to open a pull request already :)

**Comment by miaulalala** [comment]
Classic copy pasta! Apologies, `setEntityId` is of course correct.
