### ISSUE TITLE
Ressources are not shown in the Calendar

### ISSUE THREAD

**Issue by q-wertz** [nextcloud/calendar_resource_management#36]
I think something is broken. Not sure if here or in the calendar app. 
Few month ago I got that resource thing working (NC22 back then), but now after reinstalling no resources can be selected in the calendar app.

Tried it with two setups:
1. First setup:
    - NC 22.2.3
    - Calendar 3.0.1
    - Calendar Resource Management (tested these two versions):
        - `stable0.1` branch (0.1.0)
        - `main` branch
2. Second setup:
    - NC 23.0.0
    - Calendar: 3.0.1
    - Calendar Resource Management: `stable0.1` branch (0.1.0)

`Cron` is used for background jobs.

In both I set up a `building`, `story` and `room`, I can see all of them in the list view and the SQL database, but the calendar web interface does not show any of them.
Also tried different field entries, usage of restrictions etc.

Is there a way to debug this?

The SQL database contains these related tables:
```
| oc_calendar_appt_bookings   |
| oc_calendar_appt_configs    |
| oc_calendar_invitations     |
| oc_calendar_reminders       |
| oc_calendar_resources       |
| oc_calendar_resources_md    |
| oc_calendar_rooms           |
| oc_calendar_rooms_md        |
| oc_calendarchanges          |
| oc_calendarobjects          |
| oc_calendarobjects_props    |
| oc_calendars                |
| oc_calendarsubscriptions    |
| oc_calresources_buildings   |
| oc_calresources_resources   |
| oc_calresources_restricts   |
| oc_calresources_rooms       |
| oc_calresources_stories     |
| oc_calresources_vehicles    |
```

As far as I understand it the `oc_calendar_*` are unused?

**Comment by jonathanmmm** [comment]
same by me, I can see of two entries (one that was from before) only in the admin account, but not in another account, no restrictions (at least for the second room in new building), entries are shown in databases.

Also I tried deleting and creating rooms/buildings again, but it increased the ID number, changed the ID number manually back to 1 but it still increased for the next one. Is there any way to delete all of it and just start over with ID 1 for everyone (like a complete cleanup)

**Comment by q-wertz** [comment]
Are there any differences in your SQL database between the entries?

I see none of my test resources. Also downloaded now the "official" alpha as it is described now in the Readme… Same problems…

**Comment by mir06** [comment]
Same here with NC 23.0.0, calendar 3.0.3, calendar-resource-management 0.1.0

After cron-job is run, I get the entry in `oc_calendar_rooms` but I cannot see the resource in the calendar app.

**Comment by jonathanmmm** [comment]
> same by me, I can see of two entries (one that was from before) only in the admin account, but not in another account, no restrictions (at least for the second room in new building), entries are shown in databases.
> 
> Also I tried deleting and creating rooms/buildings again, but it increased the ID number, changed the ID number manually back to 1 but it still increased for the next one. Is there any way to delete all of it and just start over with ID 1 for everyone (like a complete cleanup)

Have Nextcloud 22.2.3 (Docker nextcloud-fpm behind nginx, also in docker), calendar 3.0.3, Calendar Resource Management	0.1.1-alpha.1

**Comment by q-wertz** [comment]
Looks more like a front-end issue https://github.com/nextcloud/calendar/issues/3907#issuecomment-1047560002
