### ISSUE TITLE
Decentralized resources (feature request)

### ISSUE THREAD

**Issue by brtptrs** [nextcloud/calendar_resource_management#37]
We need the ability for teams/organisations to define/organise/manage their own resources. 

Use case:
We have a decentralized (structurally and geographically) organisation with thousands (yes) of small sub-units all sharing one NC platform. Each sub-unit has its own campus and set of resources.
Managing all of these resources centrally is not viable.

Proposal:
1) A team (circle?) can define: campus, buildings, rooms, vehicles, beamer, ...
2) Visibility and access is defined by the owners (circle?)
3) Availability in calendar depends on membership and/or access rules in circles

**Comment by ChristophWurst** [comment]
I think this should go on https://help.nextcloud.com/c/apps/app-ideas/21. This app won't do this. It's one of the possible back-ends and right now there are no plans to delegate the room management from admins to users.
