### ISSUE TITLE
Resources added via CLI are not found in Calendar

### ISSUE THREAD

**Issue by miaulalala** [nextcloud/calendar_resource_management#51]
The Job that is supposed to update the Calendar Rooms and Resources is not findng any backends in some cases but for others it works fine (like @ChristophWurst ).

Backends are collected in \OCP\Calendar\Room\IManager::getBackends

**Comment by kpieth** [comment]
I have the same problem. Resources are not shown in the calendar, but with calendar-resource:resources:list. Cron.php is running. Do you have anything i can test/debug?

**Comment by rocramer** [comment]
Same problem. I can see created resources on the CLI, but they can't be found via calendar.

**Comment by smallfish01** [comment]
Same problem, who knows how to debug ?

**Comment by miaulalala** [comment]
I just played around with some stuff and tested the job that is syncing the backend resources. Every second run does not trigger the `run` method - the job gets constructed, but doesn't run. Seems like there is something else going on.

Anyone here able to debug this too?

**Comment by bilyboy785** [comment]
Any news on this issue ?

**Comment by mark543g** [comment]
Maybe.....Need enter keywords in the search bar
![D_ROOM](https://user-images.githubusercontent.com/101470270/203709726-620e7939-8e56-411e-a908-18b3ce8a7bf3.jpg)

**Comment by bilyboy785** [comment]
@mark543g it doesn't work. Resources exists, but nothing found in the UI : 

![CleanShot 2022-11-24 at 08 11 48](https://user-images.githubusercontent.com/7370044/203717401-780f30e5-2146-44b4-8680-98636c1b3299.png)

![CleanShot 2022-11-24 at 08 12 47](https://user-images.githubusercontent.com/7370044/203717447-7b827957-f35d-4feb-890e-8e132c861225.png)

**Comment by mark543g** [comment]
check table "oc_calresources_rooms" 
when i use "select * from oc_calresources_rooms;"   ,that can show echo item

btw  my nextcloud ver is 25.0.1
![db_rooms](https://user-images.githubusercontent.com/101470270/203728083-3a64fd5f-6677-4977-81a4-777e68839ee0.jpg)

**Comment by bilyboy785** [comment]
My table calresources_rooms is empty : 

`MariaDB [nextcloud]> select * from calresources_rooms;
Empty set (0.001 sec)`

**Comment by miaulalala** [comment]
> My table calresources_rooms is empty :
> 
> `MariaDB [nextcloud]> select * from calresources_rooms; Empty set (0.001 sec)`

that is a good hint, thanks. I'm not sure but this could be an issue with how we formed the query. 

Can you add an entry to your calresources_rooms table and see if that works?

**Comment by mark543g** [comment]
> select * from calresources_vehicles;

The new version databas does not have this table  (calresources_vehicles )
only "oc_calresources_vehicles" 
but...nextcloud database table does not have  table  "oc_calendar_vehicles"
maybe ...The new version does not support vehicles

**Comment by mark543g** [comment]
m.............It works

![occ_veh](https://
![vehicle_01](https://user-images.githubusercontent.com/101470270/204431513-611c6e81-e75d-4609-ac3f-ab67074b31e8.png)
user-images.githubusercontent.com/101470270/204431500-0f09e818-1a17-4925-803a-48e4f5432260.png)

**Comment by bilyboy785** [comment]
Hey @mark543g how do you make it works ? Did u create the table oc_calendar_vehicles ?

**Comment by mark543g** [comment]
> Hey @mark543g how do you make it works ? Did u create the table oc_calendar_vehicles ?
 also at talble "oc_calendar_resources"
![vehicle_on_resource](https://user-images.githubusercontent.com/101470270/204478972-386fdba5-88f3-4487-8149-b955cf27ef86.png)

**Comment by derBobby** [comment]
I had the same problem and could fix it with the following steps.
But I can't tell which steps are mandatory and which could have skipped.

1. Save the table definition ("SHOW CREATE TABLE <table>")
2. Drop all tables
3. Remove the plugin
4. Restart Docker container
5. Install the plugin
6. Needed to create the tables MANUALLY, I don't know why
7. Created my calendar resources

```
SHOW CREATE TABLE calresources_restricts;
SHOW CREATE TABLE calresources_vehicles;
SHOW CREATE TABLE calresources_rooms;
SHOW CREATE TABLE calresources_resources;
SHOW CREATE TABLE calresources_stories;
SHOW CREATE TABLE calresources_buildings;
```

**Comment by strozzascotte** [comment]
Hi, I have the same issue on Nextcloud Hub 3 (25.0.4).

1. When I added the **first room**, it appeared in oc_calendars_roooms and a calendar for the room was created in oc_calendars. Everything worked.

3. When I added a **2nd room**, the 2nd room didn't appear in the oc_calendar_rooms table and no calendar was created for the room in oc_calendars. 

I hope it helps.

**Comment by ChristophWurst** [comment]
I don't think there even should be a calendar for a room or resource.

**Comment by sangdrax8** [comment]
I have seen similar issues.  I created 2 buildings, floors, and meeting rooms.  These all showed up eventually (I didn't check it exactly 5 minutes after).  I then decided to change my naming scheme and deleted the rooms, and then re-added with my new values.  The calendar continues to show the old room names.  I ran the cron to ensure it was run, I rebooted the box, nothing seemed to cause them to sync.  I eventually went to the administration settings -> Basic Settings and switched it to AJAX syncing.  I then went to the calendar and my new rooms were there.  I then reverted the setting back to running with cron.

This isn't a good solution, but since this is a testing instance it was ok for me.  It seems the cron sync is an issue (or is it being to smart and choosing to not sync just because cron ran?)

**Comment by kousu** [comment]
I am seeing this with

* NC 25.0.9
* Calendar 4.4.4
* Calendar Resource Management 0.5.0

I have these resources set up:

<details><summary>calendar-resource:resources:list</summary>

```
www-data@org:~/nextcloud$ php occ calendar-resource:resources:list
Buildings:
+----+--------------+---------+--------------------------------------+-----------------------+
| ID | Name         | Address | Description                          | Wheelchair Accessible |
+----+--------------+---------+--------------------------------------+-----------------------+
| 2  | Bar          |         |                                      | no                    |
| 1  | Gear         |         | pool of gear and equipment           | no                    |
+----+--------------+---------+--------------------------------------+-----------------------+
Stories:
+----+------------+-----------------+
| ID | Located in | Display Name    |
+----+------------+-----------------+
| 1  | Bar        | Rez de Chaussee |
+----+------------+-----------------+
Rooms:
+----+---------+------+----------------------+-------------------------+-----------+----------------+----------+-------------+-------+--------------------+----+-----------+------------+-----------------------+
| ID | UID     | Name | Located in           | Email                   | Room Type | Contact Person | Capacity | Room Number | Phone | Video Conferencing | TV | Projector | Whiteboard | Wheelchair Accessible |
+----+---------+------+----------------------+-------------------------+-----------+----------------+----------+-------------+-------+--------------------+----+-----------+------------+-----------------------+
| 1  | bar_rdc | Bar  | Bar, Rez de Chaussee | admin+bar@example.org   | salle     |                | 0        |             | no    | no                 | no | no        | no         | no                    |
+----+---------+------+----------------------+-------------------------+-----------+----------------+----------+-------------+-------+--------------------+----+-----------+------------+-----------------------+
Resources:
+----+----------------+-----------------------+----------------+----------------+----------------+
| ID | UID            | Name                  | Located in     | Contact Person | Type           |
+----+----------------+-----------------------+----------------+----------------+----------------+
| 1  | admin          | Epson Projector       | 1 Gear         |                | projector      |
| 2  | stripperpole   | Stripper Pole         | 1 Gear         |                | dance_pole     |
+----+----------------+-----------------------+----------------+----------------+----------------+
Vehicles:
+----+-----+------+------------+-------+----------------+------+------+-------+----------+-------+----------+
| ID | UID | Name | Located in | Email | Contact Person | Type | Make | Model | Electric | Range | Capacity |
+----+-----+------+------------+-------+----------------+------+------+-------+----------+-------+----------+
Restrictions:
+----+--------+-----------+---------------+
| ID | Entity | Entity ID | Restricted To |
+----+--------+-----------+---------------+
```

</details>

I'm using cron and it has run:

![2023-08-18-172202_1018x459_scrot](https://github.com/nextcloud/calendar_resource_management/assets/987487/5ced9c84-ec08-4c56-98b4-a531b4b706e9)

But nothing shows when I search:

![2023-08-18-172237_1366x768_scrot](https://github.com/nextcloud/calendar_resource_management/assets/987487/5c9c3cf4-12e3-47a7-9d71-f6a40116815a)


---

I tried switching to "Background jobs = AJAX" like sangdrax8 suggested, but it didn't help.

**Comment by kousu** [comment]
I looked in the database, and found two tables, one of which is empty:

```
MariaDB [nextcloud]> select * from oc_calresources_resources;
+----+-------------+----------------+-----------------------+---------------------------------+----------------+------------------------+
| id | building_id | uid            | display_name          | email                           | resource_type  | contact_person_user_id |
+----+-------------+----------------+-----------------------+---------------------------------+----------------+------------------------+
|  1 |           1 | projector1     | Epson Projector       | admin@example.org               | projector      |                        |
|  4 |           1 | stripperpole   | Stripper Pole         | admin+stripperpole@example.org  | dance_pole     |                        |
+----+-------------+----------------+-----------------------+---------------------------------+----------------+------------------------+
5 rows in set (0.000 sec)

```

```
MariaDB [nextcloud]> select * from oc_calendar_resources;
Empty set (0.000 sec)
MariaDB [nextcloud]> show create table oc_calendar_resources;
+-----------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table                 | Create Table                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
+-----------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| oc_calendar_resources | CREATE TABLE `oc_calendar_resources` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `backend_id` varchar(64) DEFAULT NULL,
  `resource_id` varchar(64) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `displayname` varchar(255) DEFAULT NULL,
  `group_restrictions` varchar(4000) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `calendar_resources_bkdrsc` (`backend_id`,`resource_id`),
  KEY `calendar_resources_email` (`email`),
  KEY `calendar_resources_name` (`displayname`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin |
+-----------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

So I think I see what's going on: `oc_calresources_*` are the tables managed by this plugin, but `oc_calendar_resources` is what hooks up the Calendar app to this plugin, and for some reason it's empty. I don't know why. It's like installing the plugin missed a step -- it should have registered itself, but it didn't.

Does anyone know what `backend_id` should be? Is it `1`? or `calresources`?

I did

```
MariaDB [nextcloud]> insert into oc_calendar_resources (backend_id, resource_id, email, displayname) values ("calresource", "stripperpole", "admin+stripperpole@yota.space", "Stripper Pole");
Query OK, 1 row affected (0.003 sec)
```

and then it shows up in the Calendar search!

![2023-08-18-174523_1366x768_scrot](https://github.com/nextcloud/calendar_resource_management/assets/987487/593dd4cd-1b10-4983-a0a6-e9cbbbdf2d89)


but it doesn't work right, it can't confirm the availability nor book the item (presumably because I got `backend_id` or `resource_id` wrong)

![2023-08-18-174537_353x73_scrot](https://github.com/nextcloud/calendar_resource_management/assets/987487/1939305e-7d1e-4c88-b77a-62efbce813e5)

**Comment by kousu** [comment]
Hang on, I waited about 15 minutes, and now:

```
MariaDB [nextcloud]> select * from oc_calendar_resources;
+----+------------------------------+----------------+---------------------------------+-----------------------+--------------------+
| id | backend_id                   | resource_id    | email                           | displayname           | group_restrictions |
+----+------------------------------+----------------+---------------------------------+-----------------------+--------------------+
|  1 | calresource                  | stripperpole   | admin+stripperpole@example.org  | Stripper Pole         | NULL               |
|  2 | calendar_resource_management | admin          | admin@example.org               | Epson Projector       | []                 |
|  3 | calendar_resource_management | stripperpole   | admin+stripperpole@example.org  | Stripper Pole         | []                 |
+----+------------------------------+----------------+---------------------------------+-----------------------+--------------------+
```

and it shows up in the UI:

![2023-08-18-183239_1366x768_scrot](https://github.com/nextcloud/calendar_resource_management/assets/987487/7b1a9770-a058-41ee-ae38-ec012c6b43fe)

I deleted the one I hacked in

```
MariaDB [nextcloud]> delete from oc_calendar_resources where backend_id = 'calresource';
Query OK, 1 row affected (0.001 sec)
```

and then I tried booking it again. It took, I guess, but it still doesn't seem to be able to successfully Check Availability:

![2023-08-18-174537_353x73_scrot](https://github.com/nextcloud/calendar_resource_management/assets/987487/3e4426be-b290-4581-b6af-23c1f88b3d38)


---

So I don't know what's going on, but obviously `UpdateCalendarResourcesRoomsBackgroundJob` isn't actually being run according to the cron schedule.

Do we know if there's a specific schedule? https://docs.nextcloud.com/server/latest/admin_manual/groupware/calendar.html#resources-and-rooms just says 

> Nextcloud periodically queries all registered backends, therefore new/updated resources and rooms will show with a delay.

which isn't very helpful for first time users.

So @sangdrax8 and @derBobby, maybe what you did actually had no effect, except to slow down your efforts long enough that the background job could run and fill in `oc_calendar_resources`.

**Comment by christianlupus** [comment]
Just FYI, as I was affected by this: The background job only runs [once an hour](https://github.com/nextcloud/server/blob/cb4e367a22232f2ad2f92b924577c7cddb76877e/apps/dav/lib/BackgroundJob/UpdateCalendarResourcesRoomsBackgroundJob.php#L68-L70). So, you have to be patient when creating a new room.

**Comment by Djiock** [comment]
I'm having the same issue, a room created several days ago via cli (cron running fine) doesn't show up. I can see it in db though :
```
select * from oc_calresources_rooms\G
*************************** 1. row ***************************
                      id: 1
                story_id: 1
                     uid: Salle 41
            display_name: Salle 41 Numérique
                   email: salle41.6p-nord-est@xxxxxx.org
               room_type: Salle de réunion
  contact_person_user_id: 
                capacity: 10
             room_number: 41
               has_phone: 0
  has_video_conferencing: 0
                  has_tv: 0
           has_projector: 0
          has_whiteboard: 0
is_wheelchair_accessible: 0
1 row in set (0.000 sec)

``` 
No idea what could be missing...

**Comment by st3iny** [comment]
Starting from Nextcloud 30, there will be instant updates of rooms and resources.

Public OCP api: https://github.com/nextcloud/server/pull/45532
PR to implement it: #126

**Comment by st3iny** [comment]
Is done via #126 and will be part of the next minor release.

**Comment by MaykGyver** [comment]
With…
  * nextcloud: 29.0.16.2
  * calendar: 4.7.16
  * calendar_resource_management: 0.9.0 (newly installed)

…rooms created on cli do not show up. Traced the problem to the point, that there is no **UpdateCalendarResourcesRoomsBackgroundJob** in *oc_jobs* nor `occ background-job:list` respectively.

Previous posts lead me to the suspicion, that updating might rebuild the background job schedule and fix the missing job. st3iny's post hints even more reasons to upgrade. If my instance was small and had fewer restrictions/dependencies, I would upgrade to nc30 right now.

My instance is huge and there are defined maintenance windows for the major upgrade. That means, I can not upgrade to nc30 (yet). Has anyone any idea, how one may trigger a rebuild of the background job schedule?

**Comment by st3iny** [comment]
@MaykGyver The update is now being done synchronously starting from Nextcloud 30. So you don't need the background job anymore. I highly recommend updating your Nextcloud server.

**Comment by st3iny** [comment]
I created an issue to track this here: https://github.com/nextcloud/calendar_resource_management/issues/184
