### ISSUE TITLE
Unable to Install

### ISSUE THREAD

**Issue by xeruf** [nextcloud/calendar_resource_management#59]
### Steps to reproduce

Nextcloud Version 23.0.3

Try to install

### Expected behavior

I can install the app

### Actual behavior

```sh
❯ occ app:install calendar_resource_management
Error: Could not download app calendar_resource_management
command terminated with exit code 1
```

Neither can I manually find it in the integrations category in my Nextcloud.

### App version

Nextcloud Version 23.0.3

**Comment by st3iny** [comment]
The app has only recently been released on the app store (2022-09-11). It should work now.
