### ISSUE TITLE
Flexibility to make it multi purpose

### ISSUE THREAD

**Issue by hansimausisteffiwurstbrot** [nextcloud/calendar_resource_management#6]
Hey, 
as there is no documentation yet it might all be part of it, but having spend some time looking for a FOSS multi-purpose sharing platform, I'm really excited that Nextcloud is working on the feature. [I once posted it as a app idea](https://help.nextcloud.com/t/nextcloud-as-a-real-sharing-platform/60365). 

Imho it would be great to make it as flexible as possible, to be able to share not only rooms, but tools and bikes etc. And not only within companies and universities but other types of communities. With the ability to specify certain users/groups/circles etc. And a simple interface to make the bookings would be great... we'll see.

Well, I'm looking forward to the documentation. :)

**Comment by ChristophWurst** [comment]
It's flexible enough to support rooms (inside buildings and stories) and *resources*. Resources are the generic assets that you want to be able to book. That will include tools, bikes and other vehicles.

**Comment by hansimausisteffiwurstbrot** [comment]
> 
> 
> It's flexible enough to support rooms (inside buildings and stories) and _resources_. Resources are the generic assets that you want to be able to book. That will include tools, bikes and other vehicles.

Great.

The flexibility then depends on the further implementation, including:
* peer2peer sharing (resources can be created by users)
* limit sharing to certain users, groups and circles
* configure availability of resources (other than 24/7)
* calendar displaying availability (guess that's thought of :)

Well, I'll let you do your job. I'd love to contribute, anything but coding :(
Looking forward to read some documentation.

We could use a part of our project funds to support it, too. Not much though...

**Comment by brtptrs** [comment]
We need the ability for teams/organisations to define/organise their own resources.
Use case:
We have a decentralized organisation with thousands (yes) of small sub-units all sharing one NC platform. Each sub-unit has its own set of resources.
Managing all these resources centrally is not viable.
