### ISSUE TITLE
Support localization

### ISSUE THREAD

**Issue by p-bo** [nextcloud/calendar_resource_management#69]
Hello, Would it be possible to follow instructions on:
https://docs.nextcloud.com/server/latest/developer_manual/basics/front-end/l10n.html
...and make your app more accessible for non-English speakers please?  Thanks :-)

**Comment by p-bo** [comment]
Not sure, if this app is showing strings in Nextcloud UI at all - if not, please disregard (close) and sorry for noise.

**Comment by ChristophWurst** [comment]
The app doesn't render any UI.

The UI is provided by https://github.com/nextcloud/calendar. If you found any UI parts that are not localized please file a bug in that repo.
