### ISSUE TITLE
Use options instead of arguments for optional parameters

### ISSUE THREAD

**Issue by N4IR0** [nextcloud/calendar_resource_management#84]
### Is your feature request related to a problem? Please describe.

Omitting optional parameters can lead to escaping problems, it would be easier to just skip them completely.

### Describe the solution you'd like

Change optional parameters in all OCC commands to options (e.g. --address), so they can simply be omitted instead of using empty strings as placeholder.

### Describe alternatives you've considered

To avoid a BC break, both could be supported and in case of double use a corresponding error could appear that both (option and argument) cannot be used together.

### Additional context

If there's nothing against this feature request (since it could be a BC break depending on the solution), I'd be happy to add it myself and open a pull request.

**Comment by ChristophWurst** [comment]
> If there's nothing against this feature request (since it could be a BC break depending on the solution), I'd be happy to add it myself and open a pull request.

Sounds good to me. @st3iny wdyt?

**Comment by st3iny** [comment]
Yeah, that would be great!

**Comment by N4IR0** [comment]
Thanks for your feedback! Should I support both (arguments and options) to avoid a BC break or completely switch to options for optional arguments?

**Comment by st3iny** [comment]
You can drop the old cli. Required parameters should stay arguments and the rest can be demoted to options.
