### ISSUE TITLE
Error: "The "--address" option does not exist."

### ISSUE THREAD

**Issue by treborxy** [nextcloud/calendar_resource_management#87]
### Steps to reproduce

1. with ssh : php80 occ calendar-resource:building:create --address="Testweg 23, 12345 Berlin, Germany" "SpaceZ office Berlin"
2. I get the error : The "--address" option does not exist. 

### Expected behavior

The ressource should be saved.

### Actual behavior

quitting with error

### App version

0.4.0

### Additional info

NC Version 25.0.5

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/calendar_resource_management/pull/85 comes with 0.5
