### ISSUE TITLE
occ command examples

### ISSUE THREAD

**Issue by himpierre** [nextcloud/calendar_resource_management#9]
Hey now! 

Could you please give us some basic occ comand examples until the documentation is finished? Just tried to create a room but failed miserably. :-)

```
sudo -u www-data php occ calendar-resource:resource:create 1000 1000 jitsi-general himpierre@mydomain room
Could not create entry.
```

So what is the mandatory uid and building_id anyways?

cheers, h.

**Comment by bego68** [comment]
in this article are some examples:
https://help.nextcloud.com/t/22-beta-5-is-here-help-test/118560

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/calendar_resource_management/issues/4 will cover the commands.
